FROM node:16-alpine

# Create node_modules folder
RUN mkdir -p /usr/app/node_modules
# Working directory
WORKDIR /usr/app
# Copy package*.json files
COPY ./package*.json ./
# Install all dependencies
RUN npm ci
# Copy all local files to working directory
COPY . .
# Build the app
RUN npm run build
# Run as default command npm run launch
CMD ["npm", "run", "launch"]
# Expose port 3000
EXPOSE 3000